name: Create a comment on new issues

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-22.04
    steps:
      - name: "dump github context"
        run: echo '${{  toJSON(github.event) }}' | jq
        shell: bash
      # Community action: https://github.com/marketplace/actions/create-or-update-comment
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'

  comment-with-api:
    runs-on: ubuntu-22.04
    steps:
      - name: "Create comment with API"
        run: |
          gh api -X POST \
            https://api.github.com/repo/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments \
            -f body='
            Comment but from the API call not action 
            '
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Created by GitHub only for this repo and only for this run
          ORGANIZATION: ${{ github.repository_owner }}
          REPOSITORY: ${{ github.event.repository.name }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
